name: Trabalho Final Web

on: 
  workflow_dispatch:
  
jobs:
  e2e-tests:

    runs-on: ubuntu-latest

    steps:
    
    # clone do projeto para a maquina
    - uses: actions/checkout@v4
    
    # conferir a versão instalada
    - name: Node Version
      run: node --version
    
    - name: Instalando dependências
      run: npm install
    
    - name: Executando os testes
      run: npx cypress run

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled()}}
      with:
       name: relatorios
       path: |
          cypress/reports
          cypress/videos
          cypress/screenshots
        


